ParkingSystem/ParkingSystem/Controllers/CustomerController.cs
using log4net;
using ParkingSystem.Business_Layer;
using ParkingSystem.Repository;
using ParkingSystem.Repository.Security;
using ParkingSystem.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace ParkingSystem.Controllers
{
    public class CustomerController : BaseController
    {
        private ILog Log = LogManager.GetLogger(typeof(CustomerController));

        //Customer Index Page
        [CustomAuthorize(Role.Customer)]
        public ActionResult Index()
        {
          
            CommonBl commonBl = new CommonBl();
            return View("~/Views/Home/Index.cshtml",commonBl.GetCityHomeDropdown());
        }

        //Get Plot Details for autocomplete
        public ActionResult GetPlotDetails(string cityName, string plotName)
        {
            
            CustomerBl customerBl = new CustomerBl();
            return Json(customerBl.GetPlotIdForSearched(cityName, plotName), JsonRequestBehavior.AllowGet);
        }

        // Displays Slots
        [CustomAuthorize(Role.Customer,Role.Staff,Role.Plotter)]
        public ActionResult DisplaySlot(string id)
        {
            ViewBag.roles = User.roles;
            PlotBl plotBl = new PlotBl();
            return View("DisplaySlot", plotBl.SlotList(id));
        }

        // Displays Edit Profile Form
        [CustomAuthorize(Role.Customer)]
        public ActionResult EditProfile()
        {
            ViewBag.roles = User.roles;
            CustomerRepository customerRepo = new CustomerRepository();
            return View(customerRepo.GetPersonDetailsForEditing().Find(Person => Person.Id == User.PersonId));
        }

        //Edit Form Post
        [HttpPost]
        public ActionResult EditProfile(EditProfileCustomerViewModel model)
        {
            ViewBag.roles = User.roles;
            try
            {
                if (ModelState.IsValid)
                {
                    CustomerBl customerBl = new CustomerBl();
                    customerBl.EditPersonDetail(model, User.PersonId);
                    ViewBag.Message = "Details Successfully Updated";
                }
            }
            catch (Exception ex)
            {
                Log.Error(ex.Message, ex);
            }
            return View();
        }

        //Displays Booking History of the Customer
        [CustomAuthorize(Role.Customer)]
        public ActionResult DisplayVisitRecordsForCustomer()
        {
            ViewBag.roles = User.roles;
            return View();
        }

        //Get the Booking History of the Customer
        public JsonResult GetBookingHistoryOfCustomer(JqGridViewModel model)
        {
            CommonBl commonBl = new CommonBl();
            List<DisplayVisitHistoryViewModel> bookingList = commonBl.GetBookingHistory(model, User.PersonId);
            var jsonData = new
            {
                total = commonBl.GridPagination(model, bookingList.Count()),
                page = model.page,
                records = bookingList.Count(),
                rows = bookingList
            };
            return Json(jsonData, JsonRequestBehavior.AllowGet);
        }

        //Change Password
         [CustomAuthorize(Role.Customer)]
        public ActionResult ChangePassword()
        {
            ViewBag.roles = User.UserName;
            return View("_ChangePassword");
        }

        [HttpPost]
        public ActionResult ChangePassword(PasswordChangeViewModel model)
        {
           
            try
            {
                if (ModelState.IsValid)
                {
                    model.UserName = User.UserName;
                    CommonBl commonuserBl = new CommonBl();
                    model.NewPassword = commonuserBl.ComputeHash(model.ConfirmPassword, model.UserName);
                    commonuserBl.PasswordChange(model);
                    ViewBag.Message = "Details Successfully Updated";
                }
            }
            catch (Exception ex)
            {
                Log.Error(ex.Message, ex);
            }
            return View("_ChangePassword");
        }
    }
}

ParkingSystem/ParkingSystem/Controllers/StaffController.cs
using log4net;
using ParkingSystem.Business_Layer;
using ParkingSystem.Repository;
using ParkingSystem.Repository.Security;
using ParkingSystem.ViewModel;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace ParkingSystem.Controllers
{
    public class StaffController : BaseController
    {
        private ILog Log = LogManager.GetLogger(typeof(StaffController));

        // GET: Staff
        [CustomAuthorize(Role.Staff)]
        public ActionResult Index()
        {
            ViewBag.roles = User.roles;
            if (User.PersonId > 0)
            {
                StaffBl staffBl = new StaffBl();
                return View("DisplaySlot", staffBl.GetSlotsOfStaff(User.PersonId));
            }
            return View("~/Views/Shared/Error.cshtml");
        }

        //For displaying the plots in which the staff is registered
        [CustomAuthorize(Role.Staff)]
        public ActionResult DisplayPlot()
        {
            ViewBag.roles = User.roles;
            StaffBl staffBl = new StaffBl();
            return View(staffBl.GetPlotDetailsOfStaff(User.PersonId));
        }

        //For Displaying the Slots under that Plot
        //[CustomAuthorize(Role.Staff,Role.Plotter)]
        //public ActionResult DisplaySlot(int plotId)
        //{
        //    ViewBag.roles = User.roles;
        //    PlotRepository plotRepo = new PlotRepository();          
        //    return PartialView("_DisplaySlot",plotRepo.GetSectionDetailsForPlot(plotId));
        //}

        //Displays Staff Booking List
        [CustomAuthorize(Role.Staff)]
        public ActionResult BookingListOfStaff()
        {
            ViewBag.roles = User.roles;
            return View();
        }

        // Retrival of Staff Booking Details
        public JsonResult GetBookingDetailsOfStaff(JqGridViewModel model)
        {
            StaffBl staffBl = new StaffBl();
            CommonBl commonBl = new CommonBl();
            List<BookingDetailsViewModel> bookingList = staffBl.StaffBookingHistorySearch(model, User.PersonId);
            var jsonData = new
            {
                total = commonBl.GridPagination(model, bookingList.Count()),
                page = model.page,
                records = bookingList.Count(),
                rows = bookingList
            };
            return Json(jsonData, JsonRequestBehavior.AllowGet);
        }
    }
}

ParkingSystem/ParkingSystem/Views/Shared/_BookSlot.cshtml
@model ParkingSystem.ViewModel.SlotRegistrationViewModel
<div id="mainsectionhomepage">

    <center>
        <br />
        <div id="listlabel">
            Enter Car Details
        </div>
        <div id="slotregistrationdiv">
            @using (Ajax.BeginForm("BookSlot", "Plot",
         new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "mainsectionhomepage", InsertionMode = InsertionMode.Replace }))
            {

                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @ViewBag.Message

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <br />

                    @Html.HiddenFor(model => model.SlotId, new { htmlAttributes = new { @class = "form-control" } })

                    <br />
                    <div class="form-group required">
                        @Html.LabelFor(model => model.CarNumber, htmlAttributes: new { @class = "control-label col-md-4" })
                        <div class="col-md-5">
                            @Html.EditorFor(model => model.CarNumber, new { htmlAttributes = new { @class = "form-control ", required = "required" } })
                        </div>
                        <div>
                            @Html.ValidationMessageFor(model => model.CarNumber, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.CarName, htmlAttributes: new { @class = "control-label col-md-4" })
                        <div class="col-md-5">
                            @Html.EditorFor(model => model.CarName, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        <div class="col-md-1">
                            @Html.ValidationMessageFor(model => model.CarName, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.Label("Registered", htmlAttributes: new { @class = "control-label" })
                        <input id="registered" name="registered" type="checkbox" value="false" class="checkbox-inline" />
                    </div>
                    <div class="form-group" id="mobileno">
                        @Html.LabelFor(model => model.MobileNo, htmlAttributes: new { @class = "control-label col-md-4" })
                        <div class="col-md-5">
                            @Html.EditorFor(model => model.MobileNo, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        <div>@Html.ValidationMessageFor(model => model.MobileNo, "", new { @class = "text-danger" })</div>
                    </div>
                    <div class="form-group" id="custemail">
                        @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-4", type = "email" })
                        <div class="col-md-5">
                            @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control", id = "Email" } })
                        </div>
                        <div>
                            @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div>
                        <b>Date:</b> @DateTime.Now.ToString()
                    </div>
                    <br />
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-8">
                            <input type="submit" value="Book" class="btn btn-default plotregisterbtn" />
                        </div>
                    </div>
                </div>
            }
        </div>
</center>
</div>

ParkingSystem/ParkingSystem/Views/Shared/_ChangePassword.cshtml
@model ParkingSystem.ViewModel.PasswordChangeViewModel
<style>
    body {
        background: none;
         background-color: #C5E3BF;
    }
</style>
<div id="mainsectionhomepage">
    <br />
    <center><div id="listlabel">Change Password</div></center>
    <br />
    <center>
        <div id="changepassworddiv">
            @using (Ajax.BeginForm("ChangePassword", "Customer",
         new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "mainsectionhomepage", InsertionMode = InsertionMode.Replace }))
            {

                <div class="form-horizontal">
                    <span class="text-danger">@ViewBag.Message</span>
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="form-group">
                        @Html.LabelFor(model => model.NewPassword, htmlAttributes: new { @class = "control-label col-md-4" })
                        <div class="col-md-4">
                            @Html.EditorFor(model => model.NewPassword, new { htmlAttributes = new { @class = "form-control",Required="Required" } })
                            </div>
                        <div class="col-md-4">
                            @Html.ValidationMessageFor(model => model.NewPassword, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-4" })
                        <div class="col-md-4">
                            @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control",Required="Required" } })
                            </div>
                        <div class="col-md-4">
                            @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
                        </div>
                          
                    </div>

                    <div class="form-group required">
                        <div class="col-md-offset-2 col-md-8">
                            <input type="submit" value="Save" class="btn btn-default plotregisterbtn" />
                        </div>
                    </div>
                </div>
            }
        </div>
    </center>
    </div>

ParkingSystem/ParkingSystem/Views/Shared/_CustomerHeader.cshtml
@using Microsoft.AspNet.Identity
<div class="navbar navbar-inverse navbar-fixed-top headercolor">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("PARK MY CAR", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>
                    @Html.ActionLink(User.Identity.GetUserName(), "Index", "Home", routeValues: null, htmlAttributes: new { title = "Manage" })
                </li>
            </ul>
            @Html.Partial("_LoginPartialCustomer")
        </div>
    </div>
</div>

ParkingSystem/ParkingSystem/Views/Shared/_CustomerLayout.cshtml
@*@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>_CustomerLayout</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        body {
            background: #C5E3BF;
        }
    </style>
</head>
<body style="background:#C5E3BF">
    <div>@{ Html.RenderPartial("_CustomerHeader");} </div>
    <div class="container body-content">
        @RenderBody()
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    <script src="https://code.jquery.com/ui/1.12.0-rc.2/jquery-ui.min.js"></script>
    <link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/smoothness/jquery-ui.css">
    <script src="~/Scripts/PlotRegistration.js"></script>
    <link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" />
    <link href="~/Content/jquery.jqGrid/ui.jqgrid.css" rel="stylesheet" />
    <script src="~/Scripts/i18n/grid.locale-en.js"></script>
    <script src="~/Scripts/jquery.jqGrid.min.js"></script>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>*@

ParkingSystem/ParkingSystem/Views/Shared/_DisplayPlot.cshtml
@model IEnumerable<ParkingSystem.ViewModel.DisplayPlotNamePerPerson>
<div id="mainsectionhomepage">
    <div id="plotindexheading">
        <center>
            Select the Plots for Booking....
        </center>
    </div>
    <center>
        <ul>
            @foreach (var item in Model)
            {
                <li id="displayplot">
                    <center>
                        <div class="thumbnail plotdisplay success">
                            @*<a href="@Url.Action("DisplaySlot", "Plot", new { PlotId = item.PlotId })" title=" Click and Book" class="thumbnail">*@
                            <img src="~/Content/Images/PlotPic.jpg" id="plotpic" class="thumbnail" title="Click and Book" onclick="SlotDisplay(@item.PlotId);" />
                            <p style="color:green;">@Html.DisplayFor(modelItem => item.PlotName)</p>


                        </div>
                    </center>
                </li>
            }
        </ul>
    </center>
</div>

ParkingSystem/ParkingSystem/Views/Shared/_DisplaySlot.cshtml
@model IEnumerable<ParkingSystem.ViewModel.DisplaySlotNamePerSection>
<div id="mainsectionhomepage">
    <center>
        <br />
        <div id="listlabel">@Html.DisplayFor(m => m.FirstOrDefault().PlotName)</div>
        <div id="slotpicdescription">
            <b>Available</b><img src="~/Content/Images/parkmycarlogo.jpg" id="slotpic" />
            <br /><br /><b>Booked</b><img src="~/Content/Images/parkmycarlogobw.PNG" id="slotpic" />
        </div>
        <div id="slotnamedisplaydiv">
            <b id="slotdisplayheading">Click on the Slots to <span id="bookcloselb">Book</span> or <span id="bookcloselb">Close</span></b>
            <hr />
            @{ var list = Model.ToList();
             if (list.Count == 1)
             {
                @Html.DisplayFor(modelItem => list[0].SectionName)
                <br />
                 if (list[0].Status == 1)
                 {

                    <img src="~/Content/Images/parkmycarlogo.jpg" id="slotpic" title=@Html.DisplayFor(modelItem => list[0].SlotIdPerSection) onclick="BookSlot(@list[0].SlotId);" />
                 }
                 else
                 {


                    <img src="~/Content/Images/parkmycarlogobw.PNG" id="slotpic" title=@Html.DisplayFor(modelItem => list[0].SlotIdPerSection) onclick="CloseSlot(@list[0].SlotId);" />
                 }
             }
             for (int i = 0; i < list.Count - 1; i++)
             {
                 if (i == 0)
                 {
                    @Html.DisplayFor(modelItem => list[i].SectionName)
                    <br />
                 }

                 if (list.Count == 2)
                 {
                     if (list[i].SectionName == list[i + 1].SectionName)
                     {

                         if (list[i].Status == 1)
                         {
                            <img src="~/Content/Images/parkmycarlogo.jpg" id="slotpic" title=@Html.DisplayFor(modelItem => list[i].SlotIdPerSection) onclick="BookSlot(@list[i].SlotId);" />


                         }
                         else
                         {

                            <img src="~/Content/Images/parkmycarlogobw.PNG" id="slotpic" title=@Html.DisplayFor(modelItem => list[i].SlotIdPerSection) onclick="CloseSlot(@list[i].SlotId);" />
                         }

                         if (list[i + 1].Status == 1)
                         {
                            <img src="~/Content/Images/parkmycarlogo.jpg" id="slotpic" title=@Html.DisplayFor(modelItem => list[i+1].SlotIdPerSection) onclick="BookSlot(@list[i+1].SlotId);" />

                         }
                         else
                         {
                            <img src="~/Content/Images/parkmycarlogobw.PNG" id="slotpic" title=@Html.DisplayFor(modelItem => list[i+1].SlotIdPerSection) onclick="CloseSlot(@list[i+1].SlotId);" />

                         }
                         break;

                     }
                     else
                     {

                         if (list[i].Status == 1)
                         {
                            <img src="~/Content/Images/parkmycarlogo.jpg" id="slotpic" title=@Html.DisplayFor(modelItem => list[i].SlotIdPerSection) onclick="BookSlot(@list[i].SlotId);" />

                         }
                         else
                         {
                            <img src="~/Content/Images/parkmycarlogobw.PNG" id="slotpic" title=@Html.DisplayFor(modelItem => list[i].SlotIdPerSection) onclick="CloseSlot(@list[i].SlotId);" />

                         }
                        <br />
                        @Html.DisplayFor(modelItem => list[i + 1].SectionName)
                        <br />

                         if (list[i + 1].Status == 1)
                         {
                            <img src="~/Content/Images/parkmycarlogo.jpg" id="slotpic" title=@Html.DisplayFor(modelItem => list[i+1].SlotIdPerSection) onclick="BookSlot(@list[i+1].SlotId);" />

                         }
                         else
                         {
                            <img src="~/Content/Images/parkmycarlogobw.PNG" id="slotpic" title=@Html.DisplayFor(modelItem => list[i+1].SlotIdPerSection) onclick="CloseSlot(@list[i+1].SlotId);" />

                         }
                        <br />
                         break;

                     }

                 }

                 if (list[i].SectionName == list[i + 1].SectionName)
                 {

                     if (list[i].Status == 1)
                     {
                        <img src="~/Content/Images/parkmycarlogo.jpg" id="slotpic" title=@Html.DisplayFor(modelItem => list[i].SlotIdPerSection) onclick="BookSlot(@list[i].SlotId);" />

                     }
                     else
                     {
                        <img src="~/Content/Images/parkmycarlogobw.PNG" id="slotpic" title=@Html.DisplayFor(modelItem => list[i].SlotIdPerSection) onclick="CloseSlot(@list[i].SlotId);" />

                     }

                 }
                 else
                 {

                     if (list[i].Status == 1)
                     {
                        <img src="~/Content/Images/parkmycarlogo.jpg" id="slotpic" title=@Html.DisplayFor(modelItem => list[i].SlotIdPerSection) onclick="BookSlot(@list[i].SlotId);" />

                     }
                     else
                     {
                        <img src="~/Content/Images/parkmycarlogobw.PNG" id="slotpic" title=@Html.DisplayFor(modelItem => list[i].SlotIdPerSection) onclick="CloseSlot(@list[i].SlotId);" />

                     }
                    <br />
                    @Html.DisplayFor(modelItem => list[i + 1].SectionName)
                    <br />

                 }
                 if (i == list.Count - 2)
                 {
                     if (list[i].SectionName == list[i + 1].SectionName)
                     {

                         if (list[i + 1].Status == 1)
                         {
                            <img src="~/Content/Images/parkmycarlogo.jpg" id="slotpic" title=@Html.DisplayFor(modelItem => list[i+1].SlotIdPerSection) onclick="BookSlot(@list[i+1].SlotId);" />

                         }
                         else
                         {
                            <img src="~/Content/Images/parkmycarlogobw.PNG" id="slotpic" title=@Html.DisplayFor(modelItem => list[i+1].SlotIdPerSection) onclick="CloseSlot(@list[i+1].SlotId);" />

                         }

                     }
                     else
                     {

                         if (list[i + 1].Status == 1)
                         {
                            <img src="~/Content/Images/parkmycarlogo.jpg" id="slotpic" title=@Html.DisplayFor(modelItem => list[i+1].SlotIdPerSection) onclick="BookSlot(@list[i+1].SlotId);" />

                         }
                         else
                         {
                            <img src="~/Content/Images/parkmycarlogobw.PNG" id="slotpic" title=@Html.DisplayFor(modelItem => list[i+1].SlotIdPerSection) onclick="CloseSlot(@list[i+1].SlotId);" />

                         }

                     }
                 }

             }
            }
        </div>
</center>
</div>

ParkingSystem/ParkingSystem/Views/Shared/_HomeHeader.cshtml
<div class="navbar navbar-inverse navbar-fixed-top headercolor">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("PARK MY CAR", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>

ParkingSystem/ParkingSystem/Views/Shared/_HomeLayout.cshtml
@using Microsoft.AspNet.Identity
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Home</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body background="~/Content/Images/Homebg.jpg" id="bodyimage">
    @RenderSection("header", required: false)

    <div class="container body-content">

        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    <script src="https://code.jquery.com/ui/1.12.0-rc.2/jquery-ui.min.js"></script>
    <link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/smoothness/jquery-ui.css">
    <link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" />
    <link href="~/Content/jquery.jqGrid/ui.jqgrid.css" rel="stylesheet" />
    <script src="~/Scripts/i18n/grid.locale-en.js"></script>
    <script src="~/Scripts/jquery.jqGrid.min.js"></script>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ParkingSystem/ParkingSystem/Views/Shared/_LoginPartialCustomer.cshtml
@using Microsoft.AspNet.Identity
@if (Request.IsAuthenticated)
{
    using (Html.BeginForm("SignOut", "Home", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
    {
        <ul class="nav navbar-nav navbar-right headercolor">

            <li>
                @*@Html.ActionLink("Your Visit", "DisplayVisitRecordsForCustomer", "Customer")*@
                @Ajax.ActionLink("Your Visit", "DisplayVisitRecordsForCustomer", "Customer",


                    new AjaxOptions
                    {
                        HttpMethod = "GET",
                        UpdateTargetId = "mainsectionhomepage",
                        InsertionMode = InsertionMode.Replace
                    })
            </li>
            <li>

                @Ajax.ActionLink("Edit Profile", "EditProfile", "Customer",

                      new AjaxOptions
                      {
                          HttpMethod = "GET",
                          UpdateTargetId = "mainsectionhomepage",
                          InsertionMode = InsertionMode.Replace
                      })
            </li>
            <li>

                @Ajax.ActionLink("Change Password", "ChangePassword", "Customer",

                      new AjaxOptions
                      {
                          HttpMethod = "GET",
                          UpdateTargetId = "mainsectionhomepage",
                          InsertionMode = InsertionMode.Replace
                      })
            </li>
            <li>
                @Html.ActionLink("Sign Out", "SignOut", "Home")
            </li>
        </ul>
        @*<ul class="nav navbar-nav navbar-right">

            <li>
                @Html.ActionLink("Your Visit", "DisplayVisitRecordsForCustomer", "Customer")
            </li>
            <li>
                @Html.ActionLink("Edit Profile", "EditProfile", "Customer")
            </li>
            <li>
                @Html.ActionLink("Change Password", "ChangePassword", "Customer")
            </li>
            <li>
                @Html.ActionLink("Sign Out", "SignOut", "Home")
            </li>
        </ul>*@
    }
}
else
{

}

ParkingSystem/ParkingSystem/Views/Shared/_LoginPartialStaff.cshtml
@using Microsoft.AspNet.Identity
@if (Request.IsAuthenticated)
{
    using (Html.BeginForm("SignOut", "Home", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
    {
        @Html.AntiForgeryToken()

    <ul class="nav navbar-nav navbar-right headercolor">

        <li>

            @Ajax.ActionLink("BookingList", "BookingListOfStaff", "Staff",


                    new AjaxOptions
                    {
                        HttpMethod = "GET",
                        UpdateTargetId = "mainsectionhomepage",
                        InsertionMode = InsertionMode.Replace
                    })
        </li>
        <li>
            @Ajax.ActionLink("Book Slots", "DisplayPlot", "Staff",


                    new AjaxOptions
                    {
                        HttpMethod = "GET",
                        UpdateTargetId = "mainsectionhomepage",
                        InsertionMode = InsertionMode.Replace
                    })

        </li>
        <li>
            @Html.ActionLink("Sign Out", "SignOut", "Home")
        </li>
    </ul>
    }
}
else
{

}

ParkingSystem/ParkingSystem/Views/Shared/_StaffHeader.cshtml
@using Microsoft.AspNet.Identity
<div class="navbar navbar-inverse navbar-fixed-top headercolor">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("PARK MY CAR", "Index", "Staff", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>
                    @Html.ActionLink(User.Identity.GetUserName(), "Index", "Staff", routeValues: null, htmlAttributes: new { title = "Manage" })
                </li>
            </ul>
            @Html.Partial("_LoginPartialStaff")
        </div>
    </div>
</div>